management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.board.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: lake
    password: EYm0gQen7EPBidt77kwV
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    sql.init.mode: always

